'use server';

import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { ReportData } from '@/lib/types';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
    try {
        const { reportData, email, pdfBase64 }: {
            reportData: ReportData;
            email: string;
            pdfBase64: string;
        } = await request.json();

        if (!email || !reportData || !pdfBase64) {
            return NextResponse.json(
                { error: 'Email, report data, and PDF are required' },
                { status: 400 }
            );
        }

        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(email)) {
            return NextResponse.json(
                { error: 'Invalid email format' },
                { status: 400 }
            );
        }

        // Format date for email
        const dateStr = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        // Send email with Resend
        const { data, error } = await resend.emails.send({
            from: 'Flourish Report <hello@pathshala.site>',
            to: email,
            subject: `Your Flourishing Report - ${reportData.userInfo.name}`,
            html: `
                <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="text-align: center; margin-bottom: 30px;">
                        <h1 style="color: #b5e635; margin-bottom: 10px;">Flourish</h1>
                        <p style="color: #666;">Youth Flourishing Framework</p>
                    </div>
                    
                    <p style="color: #333; font-size: 16px; line-height: 1.6;">
                        Hi ${reportData.userInfo.name},
                    </p>
                    
                    <p style="color: #333; font-size: 16px; line-height: 1.6;">
                        Thank you for completing your Flourishing Assessment! Your personalized report is attached to this email.
                    </p>
                    
                    <div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); border-radius: 12px; padding: 20px; margin: 20px 0;">
                        <h2 style="color: #b5e635; margin-top: 0;">Your Overview</h2>
                        <p style="color: #fff;">
                            <strong>Overall Score:</strong> ${reportData.overallScore.toFixed(1)}%<br/>
                            <strong>Flourishing Domains:</strong> ${reportData.flourishingDomains} of 7<br/>
                            <strong>Generated:</strong> ${dateStr}
                        </p>
                    </div>
                    
                    <p style="color: #333; font-size: 16px; line-height: 1.6;">
                        Open the attached PDF for your complete personalized insights, recommendations, and resources.
                    </p>
                    
                    <p style="color: #666; font-size: 14px; margin-top: 30px;">
                        Keep flourishing!<br/>
                        <span style="color: #b5e635;">The Flourish Team</span>
                    </p>
                    
                    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;" />
                    
                    <p style="color: #999; font-size: 12px; text-align: center;">
                        This report was generated by the Youth Flourishing Framework.<br/>
                        <a href="https://nirman.mkcl.org" style="color: #b5e635;">Learn more about NIRMAN</a>
                    </p>
                </div>
            `,
            attachments: [
                {
                    filename: `flourish-report-${reportData.userInfo.name.replace(/\s+/g, '-').toLowerCase()}.pdf`,
                    content: pdfBase64,
                }
            ],
        });

        if (error) {
            console.error('Resend error:', error);
            return NextResponse.json(
                { error: 'Failed to send email. Please try again.' },
                { status: 500 }
            );
        }

        return NextResponse.json({
            success: true,
            messageId: data?.id,
            message: 'Report sent successfully!'
        });
    } catch (error) {
        console.error('Send report error:', error);
        return NextResponse.json(
            { error: 'Failed to send email. Please try again.' },
            { status: 500 }
        );
    }
}
